//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIMBRADOS.ServiceReferencePruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://localhost/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReferencePruebas.TimbradoSoap")]
    public interface TimbradoSoap {
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/RegistraEmisor", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse RegistraEmisor(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/RegistraEmisor", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse> RegistraEmisorAsync(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse TimbraRetencion(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse> TimbraRetencionAsync(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AsignaTimbresEmisor", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse AsignaTimbresEmisor(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AsignaTimbresEmisor", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse> AsignaTimbresEmisorAsync(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneTimbresDisponibles", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse ObtieneTimbresDisponibles(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneTimbresDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse> ObtieneTimbresDisponiblesAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse TimbraCFDI(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse> TimbraCFDIAsync(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse CancelaCFDI(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse> CancelaCFDIAsync(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDIAck", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse CancelaCFDIAck(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDIAck", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse> CancelaCFDIAckAsync(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse CancelaRetencion(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse> CancelaRetencionAsync(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse ObtieneCFDI(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse> ObtieneCFDIAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse ObtieneRetencion(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse> ObtieneRetencionAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisor", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequestBody Body;
        
        public RegistraEmisorRequest() {
        }
        
        public RegistraEmisorRequest(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string base64Cer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string base64Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public RegistraEmisorRequestBody() {
        }
        
        public RegistraEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.base64Cer = base64Cer;
            this.base64Key = base64Key;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisorResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponseBody Body;
        
        public RegistraEmisorResponse() {
        }
        
        public RegistraEmisorResponse(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType RegistraEmisorResult;
        
        public RegistraEmisorResponseBody() {
        }
        
        public RegistraEmisorResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType RegistraEmisorResult) {
            this.RegistraEmisorResult = RegistraEmisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequestBody Body;
        
        public TimbraRetencionRequest() {
        }
        
        public TimbraRetencionRequest(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlComprobanteBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idComprobante;
        
        public TimbraRetencionRequestBody() {
        }
        
        public TimbraRetencionRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.xmlComprobanteBase64 = xmlComprobanteBase64;
            this.idComprobante = idComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponseBody Body;
        
        public TimbraRetencionResponse() {
        }
        
        public TimbraRetencionResponse(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraRetencionResult;
        
        public TimbraRetencionResponseBody() {
        }
        
        public TimbraRetencionResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraRetencionResult) {
            this.TimbraRetencionResult = TimbraRetencionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignaTimbresEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignaTimbresEmisor", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequestBody Body;
        
        public AsignaTimbresEmisorRequest() {
        }
        
        public AsignaTimbresEmisorRequest(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AsignaTimbresEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int noTimbres;
        
        public AsignaTimbresEmisorRequestBody() {
        }
        
        public AsignaTimbresEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.noTimbres = noTimbres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignaTimbresEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignaTimbresEmisorResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponseBody Body;
        
        public AsignaTimbresEmisorResponse() {
        }
        
        public AsignaTimbresEmisorResponse(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AsignaTimbresEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType AsignaTimbresEmisorResult;
        
        public AsignaTimbresEmisorResponseBody() {
        }
        
        public AsignaTimbresEmisorResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType AsignaTimbresEmisorResult) {
            this.AsignaTimbresEmisorResult = AsignaTimbresEmisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneTimbresDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneTimbresDisponibles", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequestBody Body;
        
        public ObtieneTimbresDisponiblesRequest() {
        }
        
        public ObtieneTimbresDisponiblesRequest(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneTimbresDisponiblesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        public ObtieneTimbresDisponiblesRequestBody() {
        }
        
        public ObtieneTimbresDisponiblesRequestBody(string usuarioIntegrador, string rfcEmisor) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneTimbresDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneTimbresDisponiblesResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponseBody Body;
        
        public ObtieneTimbresDisponiblesResponse() {
        }
        
        public ObtieneTimbresDisponiblesResponse(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneTimbresDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneTimbresDisponiblesResult;
        
        public ObtieneTimbresDisponiblesResponseBody() {
        }
        
        public ObtieneTimbresDisponiblesResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneTimbresDisponiblesResult) {
            this.ObtieneTimbresDisponiblesResult = ObtieneTimbresDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequestBody Body;
        
        public TimbraCFDIRequest() {
        }
        
        public TimbraCFDIRequest(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlComprobanteBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idComprobante;
        
        public TimbraCFDIRequestBody() {
        }
        
        public TimbraCFDIRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.xmlComprobanteBase64 = xmlComprobanteBase64;
            this.idComprobante = idComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponseBody Body;
        
        public TimbraCFDIResponse() {
        }
        
        public TimbraCFDIResponse(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraCFDIResult;
        
        public TimbraCFDIResponseBody() {
        }
        
        public TimbraCFDIResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraCFDIResult) {
            this.TimbraCFDIResult = TimbraCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequestBody Body;
        
        public CancelaCFDIRequest() {
        }
        
        public CancelaCFDIRequest(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaCFDIRequestBody() {
        }
        
        public CancelaCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponseBody Body;
        
        public CancelaCFDIResponse() {
        }
        
        public CancelaCFDIResponse(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDIResult;
        
        public CancelaCFDIResponseBody() {
        }
        
        public CancelaCFDIResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDIResult) {
            this.CancelaCFDIResult = CancelaCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIAckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIAck", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequestBody Body;
        
        public CancelaCFDIAckRequest() {
        }
        
        public CancelaCFDIAckRequest(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIAckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaCFDIAckRequestBody() {
        }
        
        public CancelaCFDIAckRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIAckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIAckResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponseBody Body;
        
        public CancelaCFDIAckResponse() {
        }
        
        public CancelaCFDIAckResponse(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIAckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDIAckResult;
        
        public CancelaCFDIAckResponseBody() {
        }
        
        public CancelaCFDIAckResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDIAckResult) {
            this.CancelaCFDIAckResult = CancelaCFDIAckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequestBody Body;
        
        public CancelaRetencionRequest() {
        }
        
        public CancelaRetencionRequest(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaRetencionRequestBody() {
        }
        
        public CancelaRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponseBody Body;
        
        public CancelaRetencionResponse() {
        }
        
        public CancelaRetencionResponse(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaRetencionResult;
        
        public CancelaRetencionResponseBody() {
        }
        
        public CancelaRetencionResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaRetencionResult) {
            this.CancelaRetencionResult = CancelaRetencionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequestBody Body;
        
        public ObtieneCFDIRequest() {
        }
        
        public ObtieneCFDIRequest(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public ObtieneCFDIRequestBody() {
        }
        
        public ObtieneCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponseBody Body;
        
        public ObtieneCFDIResponse() {
        }
        
        public ObtieneCFDIResponse(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneCFDIResult;
        
        public ObtieneCFDIResponseBody() {
        }
        
        public ObtieneCFDIResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneCFDIResult) {
            this.ObtieneCFDIResult = ObtieneCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequestBody Body;
        
        public ObtieneRetencionRequest() {
        }
        
        public ObtieneRetencionRequest(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public ObtieneRetencionRequestBody() {
        }
        
        public ObtieneRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponseBody Body;
        
        public ObtieneRetencionResponse() {
        }
        
        public ObtieneRetencionResponse(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneRetencionResult;
        
        public ObtieneRetencionResponseBody() {
        }
        
        public ObtieneRetencionResponseBody(TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneRetencionResult) {
            this.ObtieneRetencionResult = ObtieneRetencionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimbradoSoapChannel : TIMBRADOS.ServiceReferencePruebas.TimbradoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimbradoSoapClient : System.ServiceModel.ClientBase<TIMBRADOS.ServiceReferencePruebas.TimbradoSoap>, TIMBRADOS.ServiceReferencePruebas.TimbradoSoap {
        
        public TimbradoSoapClient() {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.RegistraEmisor(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest request) {
            return base.Channel.RegistraEmisor(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType RegistraEmisor(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest inValue = new TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.base64Cer = base64Cer;
            inValue.Body.base64Key = base64Key;
            inValue.Body.contrasena = contrasena;
            TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).RegistraEmisor(inValue);
            return retVal.Body.RegistraEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.RegistraEmisorAsync(TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest request) {
            return base.Channel.RegistraEmisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.RegistraEmisorResponse> RegistraEmisorAsync(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest inValue = new TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.RegistraEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.base64Cer = base64Cer;
            inValue.Body.base64Key = base64Key;
            inValue.Body.contrasena = contrasena;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).RegistraEmisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.TimbraRetencion(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest request) {
            return base.Channel.TimbraRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraRetencion(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).TimbraRetencion(inValue);
            return retVal.Body.TimbraRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.TimbraRetencionAsync(TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest request) {
            return base.Channel.TimbraRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraRetencionResponse> TimbraRetencionAsync(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.TimbraRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).TimbraRetencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.AsignaTimbresEmisor(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest request) {
            return base.Channel.AsignaTimbresEmisor(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType AsignaTimbresEmisor(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest inValue = new TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.noTimbres = noTimbres;
            TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).AsignaTimbresEmisor(inValue);
            return retVal.Body.AsignaTimbresEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.AsignaTimbresEmisorAsync(TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest request) {
            return base.Channel.AsignaTimbresEmisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorResponse> AsignaTimbresEmisorAsync(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest inValue = new TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.AsignaTimbresEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.noTimbres = noTimbres;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).AsignaTimbresEmisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneTimbresDisponibles(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest request) {
            return base.Channel.ObtieneTimbresDisponibles(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneTimbresDisponibles(string usuarioIntegrador, string rfcEmisor) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneTimbresDisponibles(inValue);
            return retVal.Body.ObtieneTimbresDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneTimbresDisponiblesAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest request) {
            return base.Channel.ObtieneTimbresDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesResponse> ObtieneTimbresDisponiblesAsync(string usuarioIntegrador, string rfcEmisor) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneTimbresDisponiblesRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneTimbresDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.TimbraCFDI(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest request) {
            return base.Channel.TimbraCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType TimbraCFDI(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).TimbraCFDI(inValue);
            return retVal.Body.TimbraCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.TimbraCFDIAsync(TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest request) {
            return base.Channel.TimbraCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.TimbraCFDIResponse> TimbraCFDIAsync(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.TimbraCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).TimbraCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaCFDI(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest request) {
            return base.Channel.CancelaCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaCFDI(inValue);
            return retVal.Body.CancelaCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaCFDIAsync(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest request) {
            return base.Channel.CancelaCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIResponse> CancelaCFDIAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaCFDIAck(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest request) {
            return base.Channel.CancelaCFDIAck(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaCFDIAck(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaCFDIAck(inValue);
            return retVal.Body.CancelaCFDIAckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaCFDIAckAsync(TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest request) {
            return base.Channel.CancelaCFDIAckAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckResponse> CancelaCFDIAckAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaCFDIAckRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaCFDIAckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaRetencion(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest request) {
            return base.Channel.CancelaRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType CancelaRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaRetencion(inValue);
            return retVal.Body.CancelaRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.CancelaRetencionAsync(TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest request) {
            return base.Channel.CancelaRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.CancelaRetencionResponse> CancelaRetencionAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.CancelaRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).CancelaRetencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneCFDI(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest request) {
            return base.Channel.ObtieneCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneCFDI(inValue);
            return retVal.Body.ObtieneCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneCFDIAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest request) {
            return base.Channel.ObtieneCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIResponse> ObtieneCFDIAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneRetencion(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest request) {
            return base.Channel.ObtieneRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferencePruebas.ArrayOfAnyType ObtieneRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse retVal = ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneRetencion(inValue);
            return retVal.Body.ObtieneRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse> TIMBRADOS.ServiceReferencePruebas.TimbradoSoap.ObtieneRetencionAsync(TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest request) {
            return base.Channel.ObtieneRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionResponse> ObtieneRetencionAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest inValue = new TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferencePruebas.ObtieneRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferencePruebas.TimbradoSoap)(this)).ObtieneRetencionAsync(inValue);
        }
    }
}
