//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIMBRADOS.ServiceReferenceProductivo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://localhost/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReferenceProductivo.TimbradoSoap")]
    public interface TimbradoSoap {
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/RegistraEmisor", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse RegistraEmisor(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/RegistraEmisor", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse> RegistraEmisorAsync(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse TimbraRetencion(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse> TimbraRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AsignaTimbresEmisor", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse AsignaTimbresEmisor(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AsignaTimbresEmisor", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse> AsignaTimbresEmisorAsync(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneTimbresDisponibles", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse ObtieneTimbresDisponibles(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneTimbresDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse> ObtieneTimbresDisponiblesAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse TimbraCFDI(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/TimbraCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse> TimbraCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse CancelaCFDI(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse> CancelaCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDIAck", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse CancelaCFDIAck(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaCFDIAck", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse> CancelaCFDIAckAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse CancelaRetencion(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CancelaRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse> CancelaRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneCFDI", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse ObtieneCFDI(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse> ObtieneCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest request);
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneRetencion", ReplyAction="*")]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse ObtieneRetencion(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtieneRetencion", ReplyAction="*")]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse> ObtieneRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisor", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequestBody Body;
        
        public RegistraEmisorRequest() {
        }
        
        public RegistraEmisorRequest(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string base64Cer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string base64Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public RegistraEmisorRequestBody() {
        }
        
        public RegistraEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.base64Cer = base64Cer;
            this.base64Key = base64Key;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraEmisorResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponseBody Body;
        
        public RegistraEmisorResponse() {
        }
        
        public RegistraEmisorResponse(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class RegistraEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType RegistraEmisorResult;
        
        public RegistraEmisorResponseBody() {
        }
        
        public RegistraEmisorResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType RegistraEmisorResult) {
            this.RegistraEmisorResult = RegistraEmisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequestBody Body;
        
        public TimbraRetencionRequest() {
        }
        
        public TimbraRetencionRequest(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlComprobanteBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idComprobante;
        
        public TimbraRetencionRequestBody() {
        }
        
        public TimbraRetencionRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.xmlComprobanteBase64 = xmlComprobanteBase64;
            this.idComprobante = idComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponseBody Body;
        
        public TimbraRetencionResponse() {
        }
        
        public TimbraRetencionResponse(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraRetencionResult;
        
        public TimbraRetencionResponseBody() {
        }
        
        public TimbraRetencionResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraRetencionResult) {
            this.TimbraRetencionResult = TimbraRetencionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignaTimbresEmisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignaTimbresEmisor", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequestBody Body;
        
        public AsignaTimbresEmisorRequest() {
        }
        
        public AsignaTimbresEmisorRequest(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AsignaTimbresEmisorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int noTimbres;
        
        public AsignaTimbresEmisorRequestBody() {
        }
        
        public AsignaTimbresEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.noTimbres = noTimbres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsignaTimbresEmisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsignaTimbresEmisorResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponseBody Body;
        
        public AsignaTimbresEmisorResponse() {
        }
        
        public AsignaTimbresEmisorResponse(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AsignaTimbresEmisorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType AsignaTimbresEmisorResult;
        
        public AsignaTimbresEmisorResponseBody() {
        }
        
        public AsignaTimbresEmisorResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType AsignaTimbresEmisorResult) {
            this.AsignaTimbresEmisorResult = AsignaTimbresEmisorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneTimbresDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneTimbresDisponibles", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequestBody Body;
        
        public ObtieneTimbresDisponiblesRequest() {
        }
        
        public ObtieneTimbresDisponiblesRequest(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneTimbresDisponiblesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        public ObtieneTimbresDisponiblesRequestBody() {
        }
        
        public ObtieneTimbresDisponiblesRequestBody(string usuarioIntegrador, string rfcEmisor) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneTimbresDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneTimbresDisponiblesResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponseBody Body;
        
        public ObtieneTimbresDisponiblesResponse() {
        }
        
        public ObtieneTimbresDisponiblesResponse(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneTimbresDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneTimbresDisponiblesResult;
        
        public ObtieneTimbresDisponiblesResponseBody() {
        }
        
        public ObtieneTimbresDisponiblesResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneTimbresDisponiblesResult) {
            this.ObtieneTimbresDisponiblesResult = ObtieneTimbresDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequestBody Body;
        
        public TimbraCFDIRequest() {
        }
        
        public TimbraCFDIRequest(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlComprobanteBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idComprobante;
        
        public TimbraCFDIRequestBody() {
        }
        
        public TimbraCFDIRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.xmlComprobanteBase64 = xmlComprobanteBase64;
            this.idComprobante = idComprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbraCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbraCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponseBody Body;
        
        public TimbraCFDIResponse() {
        }
        
        public TimbraCFDIResponse(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class TimbraCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraCFDIResult;
        
        public TimbraCFDIResponseBody() {
        }
        
        public TimbraCFDIResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraCFDIResult) {
            this.TimbraCFDIResult = TimbraCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequestBody Body;
        
        public CancelaCFDIRequest() {
        }
        
        public CancelaCFDIRequest(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaCFDIRequestBody() {
        }
        
        public CancelaCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponseBody Body;
        
        public CancelaCFDIResponse() {
        }
        
        public CancelaCFDIResponse(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDIResult;
        
        public CancelaCFDIResponseBody() {
        }
        
        public CancelaCFDIResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDIResult) {
            this.CancelaCFDIResult = CancelaCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIAckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIAck", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequestBody Body;
        
        public CancelaCFDIAckRequest() {
        }
        
        public CancelaCFDIAckRequest(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIAckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaCFDIAckRequestBody() {
        }
        
        public CancelaCFDIAckRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaCFDIAckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaCFDIAckResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponseBody Body;
        
        public CancelaCFDIAckResponse() {
        }
        
        public CancelaCFDIAckResponse(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaCFDIAckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDIAckResult;
        
        public CancelaCFDIAckResponseBody() {
        }
        
        public CancelaCFDIAckResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDIAckResult) {
            this.CancelaCFDIAckResult = CancelaCFDIAckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequestBody Body;
        
        public CancelaRetencionRequest() {
        }
        
        public CancelaRetencionRequest(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public CancelaRetencionRequestBody() {
        }
        
        public CancelaRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponseBody Body;
        
        public CancelaRetencionResponse() {
        }
        
        public CancelaRetencionResponse(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CancelaRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaRetencionResult;
        
        public CancelaRetencionResponseBody() {
        }
        
        public CancelaRetencionResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaRetencionResult) {
            this.CancelaRetencionResult = CancelaRetencionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDI", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequestBody Body;
        
        public ObtieneCFDIRequest() {
        }
        
        public ObtieneCFDIRequest(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public ObtieneCFDIRequestBody() {
        }
        
        public ObtieneCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneCFDIResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponseBody Body;
        
        public ObtieneCFDIResponse() {
        }
        
        public ObtieneCFDIResponse(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneCFDIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneCFDIResult;
        
        public ObtieneCFDIResponseBody() {
        }
        
        public ObtieneCFDIResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneCFDIResult) {
            this.ObtieneCFDIResult = ObtieneCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneRetencion", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequestBody Body;
        
        public ObtieneRetencionRequest() {
        }
        
        public ObtieneRetencionRequest(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folioUUID;
        
        public ObtieneRetencionRequestBody() {
        }
        
        public ObtieneRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.folioUUID = folioUUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtieneRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtieneRetencionResponse", Namespace="http://localhost/", Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponseBody Body;
        
        public ObtieneRetencionResponse() {
        }
        
        public ObtieneRetencionResponse(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ObtieneRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneRetencionResult;
        
        public ObtieneRetencionResponseBody() {
        }
        
        public ObtieneRetencionResponseBody(TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneRetencionResult) {
            this.ObtieneRetencionResult = ObtieneRetencionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimbradoSoapChannel : TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimbradoSoapClient : System.ServiceModel.ClientBase<TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap>, TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap {
        
        public TimbradoSoapClient() {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.RegistraEmisor(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest request) {
            return base.Channel.RegistraEmisor(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType RegistraEmisor(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.base64Cer = base64Cer;
            inValue.Body.base64Key = base64Key;
            inValue.Body.contrasena = contrasena;
            TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).RegistraEmisor(inValue);
            return retVal.Body.RegistraEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.RegistraEmisorAsync(TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest request) {
            return base.Channel.RegistraEmisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorResponse> RegistraEmisorAsync(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena) {
            TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.RegistraEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.base64Cer = base64Cer;
            inValue.Body.base64Key = base64Key;
            inValue.Body.contrasena = contrasena;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).RegistraEmisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.TimbraRetencion(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest request) {
            return base.Channel.TimbraRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraRetencion(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).TimbraRetencion(inValue);
            return retVal.Body.TimbraRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.TimbraRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest request) {
            return base.Channel.TimbraRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionResponse> TimbraRetencionAsync(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.TimbraRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).TimbraRetencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.AsignaTimbresEmisor(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest request) {
            return base.Channel.AsignaTimbresEmisor(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType AsignaTimbresEmisor(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.noTimbres = noTimbres;
            TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).AsignaTimbresEmisor(inValue);
            return retVal.Body.AsignaTimbresEmisorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.AsignaTimbresEmisorAsync(TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest request) {
            return base.Channel.AsignaTimbresEmisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorResponse> AsignaTimbresEmisorAsync(string usuarioIntegrador, string rfcEmisor, int noTimbres) {
            TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.AsignaTimbresEmisorRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.noTimbres = noTimbres;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).AsignaTimbresEmisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneTimbresDisponibles(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest request) {
            return base.Channel.ObtieneTimbresDisponibles(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneTimbresDisponibles(string usuarioIntegrador, string rfcEmisor) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneTimbresDisponibles(inValue);
            return retVal.Body.ObtieneTimbresDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneTimbresDisponiblesAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest request) {
            return base.Channel.ObtieneTimbresDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesResponse> ObtieneTimbresDisponiblesAsync(string usuarioIntegrador, string rfcEmisor) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneTimbresDisponiblesRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneTimbresDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.TimbraCFDI(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest request) {
            return base.Channel.TimbraCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType TimbraCFDI(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).TimbraCFDI(inValue);
            return retVal.Body.TimbraCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.TimbraCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest request) {
            return base.Channel.TimbraCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIResponse> TimbraCFDIAsync(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante) {
            TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.TimbraCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
            inValue.Body.idComprobante = idComprobante;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).TimbraCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaCFDI(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest request) {
            return base.Channel.CancelaCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaCFDI(inValue);
            return retVal.Body.CancelaCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest request) {
            return base.Channel.CancelaCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIResponse> CancelaCFDIAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaCFDIAck(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest request) {
            return base.Channel.CancelaCFDIAck(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaCFDIAck(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaCFDIAck(inValue);
            return retVal.Body.CancelaCFDIAckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaCFDIAckAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest request) {
            return base.Channel.CancelaCFDIAckAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckResponse> CancelaCFDIAckAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaCFDIAckRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaCFDIAckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaRetencion(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest request) {
            return base.Channel.CancelaRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType CancelaRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaRetencion(inValue);
            return retVal.Body.CancelaRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.CancelaRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest request) {
            return base.Channel.CancelaRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionResponse> CancelaRetencionAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.CancelaRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).CancelaRetencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneCFDI(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest request) {
            return base.Channel.ObtieneCFDI(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneCFDI(inValue);
            return retVal.Body.ObtieneCFDIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneCFDIAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest request) {
            return base.Channel.ObtieneCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIResponse> ObtieneCFDIAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneCFDIRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneRetencion(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest request) {
            return base.Channel.ObtieneRetencion(request);
        }
        
        public TIMBRADOS.ServiceReferenceProductivo.ArrayOfAnyType ObtieneRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse retVal = ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneRetencion(inValue);
            return retVal.Body.ObtieneRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse> TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap.ObtieneRetencionAsync(TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest request) {
            return base.Channel.ObtieneRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionResponse> ObtieneRetencionAsync(string usuarioIntegrador, string rfcEmisor, string folioUUID) {
            TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest inValue = new TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequest();
            inValue.Body = new TIMBRADOS.ServiceReferenceProductivo.ObtieneRetencionRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.folioUUID = folioUUID;
            return ((TIMBRADOS.ServiceReferenceProductivo.TimbradoSoap)(this)).ObtieneRetencionAsync(inValue);
        }
    }
}
